const MAX_METADATA_LENGTH = 127;
const SAMPLE_SECURITY_ROOT = "3ViC8TJ32EHYFTXhBKSqqsPTQWyTSToNPxnBCkn4eRSe";
const BURNER_ADDRESS = "AU9Qeik8BpBbiNnsDsxu5DVtpr6VGZBVRBdY3SSsSk1gXoNGX7Xp";

module.exports = {
  MAX_METADATA_LENGTH: MAX_METADATA_LENGTH,
  BURNER_ADDRESS: BURNER_ADDRESS,
  SAMPLE_SECURITY_ROOT: SAMPLE_SECURITY_ROOT
};
