const BN = require("bn.js");

const MAX_INTEGER = new BN("FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF", 16);
const MAX_METADATA_LENGTH = 127;
const SAMPLE_SECURITY_ROOT = "3ViC8TJ32EHYFTXhBKSqqsPTQWyTSToNPxnBCkn4eRSe";

module.export = {
  MAX_INTGER: MAX_INTEGER,
  MAX_METADATA_LENGTH: MAX_METADATA_LENGTH,
  SAMPLE_SECURITY_ROOT: SAMPLE_SECURITY_ROOT
};
