name: tests
on: 
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: Use Node.jobs
          uses: actions/setup-node@v1
          with:
            node-version: '16.2.0'
        - run: npm install
        - run: npm run test
          env: 
            CI: true
